ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = votacao;

-- Modelo do cérebro: docs/cerebro/02-negocio/Entidades.md
-- Tabelas: partido, municipio, zona, secao, eleitor, eleicao, cargo, candidatura, voto, comparecimento

CREATE TABLE partido (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero NUMBER NOT NULL,
    sigla VARCHAR2(20) NOT NULL,
    nome VARCHAR2(200) NOT NULL,
    ativo NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE municipio (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(200) NOT NULL,
    uf VARCHAR2(2) NOT NULL
);

CREATE TABLE zona (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero NUMBER NOT NULL,
    municipio_id NUMBER NOT NULL,
    CONSTRAINT fk_zona_municipio FOREIGN KEY (municipio_id) REFERENCES municipio (id)
);

CREATE TABLE secao (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero NUMBER NOT NULL,
    zona_id NUMBER NOT NULL,
    local VARCHAR2(200),
    CONSTRAINT fk_secao_zona FOREIGN KEY (zona_id) REFERENCES zona (id)
);

CREATE TABLE eleitor (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(20) NOT NULL,
    cpf VARCHAR2(14),
    nome VARCHAR2(200) NOT NULL,
    zona_id NUMBER NOT NULL,
    secao_id NUMBER NOT NULL,
    ativo NUMBER(1) DEFAULT 1 NOT NULL,
    votou NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT uk_eleitor_titulo UNIQUE (titulo),
    CONSTRAINT fk_eleitor_zona FOREIGN KEY (zona_id) REFERENCES zona (id),
    CONSTRAINT fk_eleitor_secao FOREIGN KEY (secao_id) REFERENCES secao (id)
);

CREATE TABLE eleicao (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(200) NOT NULL,
    ano NUMBER NOT NULL,
    data_turno1 DATE NOT NULL,
    data_turno2 DATE,
    turno_atual NUMBER NOT NULL,
    segundo_turno_habilitado NUMBER(1) DEFAULT 0 NOT NULL,
    ativa NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE cargo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(200) NOT NULL,
    uf VARCHAR2(2),
    permite_segundo_turno NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE candidatura (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleitor_id NUMBER NOT NULL,
    partido_id NUMBER NOT NULL,
    eleicao_id NUMBER NOT NULL,
    cargo_id NUMBER NOT NULL,
    numero NUMBER NOT NULL,
    ativa NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT fk_candidatura_eleitor FOREIGN KEY (eleitor_id) REFERENCES eleitor (id),
    CONSTRAINT fk_candidatura_partido FOREIGN KEY (partido_id) REFERENCES partido (id),
    CONSTRAINT fk_candidatura_eleicao FOREIGN KEY (eleicao_id) REFERENCES eleicao (id),
    CONSTRAINT fk_candidatura_cargo FOREIGN KEY (cargo_id) REFERENCES cargo (id)
);

CREATE TABLE voto (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidatura_id NUMBER NOT NULL,
    eleicao_id NUMBER NOT NULL,
    turno NUMBER NOT NULL,
    zona_id NUMBER NOT NULL,
    secao_id NUMBER NOT NULL,
    CONSTRAINT fk_voto_candidatura FOREIGN KEY (candidatura_id) REFERENCES candidatura (id),
    CONSTRAINT fk_voto_eleicao FOREIGN KEY (eleicao_id) REFERENCES eleicao (id),
    CONSTRAINT fk_voto_zona FOREIGN KEY (zona_id) REFERENCES zona (id),
    CONSTRAINT fk_voto_secao FOREIGN KEY (secao_id) REFERENCES secao (id)
);

CREATE TABLE comparecimento (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleitor_id NUMBER NOT NULL,
    eleicao_id NUMBER NOT NULL,
    turno NUMBER NOT NULL,
    zona_id NUMBER NOT NULL,
    secao_id NUMBER NOT NULL,
    CONSTRAINT uk_comparecimento UNIQUE (eleitor_id, eleicao_id, turno),
    CONSTRAINT fk_comp_eleitor FOREIGN KEY (eleitor_id) REFERENCES eleitor (id),
    CONSTRAINT fk_comp_eleicao FOREIGN KEY (eleicao_id) REFERENCES eleicao (id),
    CONSTRAINT fk_comp_zona FOREIGN KEY (zona_id) REFERENCES zona (id),
    CONSTRAINT fk_comp_secao FOREIGN KEY (secao_id) REFERENCES secao (id)
);
